name: 'Actions Composite Template'
description: 'Greet someone'
branding:
  icon: "check-circle"
  color: "green"
inputs:
  ProjectOwner:
    description: 'Project Owner'
    required: true
    # default: ${{ vars.DUE_OWNER }}
  ProjectNumber:
    description: 'Project Number'
    required: true
    # default: ${{ vars.DUE_PROJECT_NUMBER }}
  DueDateFieldName:
    description: 'Field Name for Due Date'
    required: true
    # default: ${{ vars.DUE_FIELD_NAME }}
  Status:
    description: 'Status to update'
    required: true
    # default: ${{ vars.DUE_STATUS }}
  TOKEN:
    description: 'GitHub Token'
    required: true
    # default: ${{ secrets.GH_PAT }}
outputs:
  updated-count:
    description: "Number of items that have been updated"
    value: ${{steps.update-run.outputs.updated-count}}
runs:
  using: "composite"
  steps:
    - id: update-run
      shell: pwsh
      run: |

        Import-Module -Name ProjectHelper

        $param = @{
          Owner = ${{ inputs.ProjectOwner }}
          ProjectNumber = @{{ inputs.ProjectNumber}}
          DueDateFieldName = @{{ inputs.DueDateFieldName }}
          Status = @{{ inputs.Status }}
        }

        # Overdue Project Items
        echo "Overdue Project Items"
        update-ProjectItemsStatusOnDueDate @param

        $updated = (Get-ProjectItemStaged).Count
        Sync-ProjectItemStaged
        echo "updated-count=$updated" >> $GITHUB_OUTPUT

